### PR TITLE
Fix for 'Too many open files'

### PR DESCRIPTION
**Pull request by davidsiefert**
Resource leak while untarring.  Files will not get closed until the function
returns (use of defer to close files).  Extracted method to clean up the code
a little bit as well as close the open file sooner than later.  Test written
first to validate defect before fixing.

### CODE REVIEW

**Comment by c4milo** [comment]
Good catch @davidsiefert, would you mind fixing also the other functions where this can happen? mainly anywhere where we are using the defer statement within a for loop in order to close files.

**Comment by davidsiefert** [comment]
Yea this should def be a problem in the unzip function as well.  I can fix and submit another patch/PR sometime soon.  Would it be cool to get this merged in for anybody depending on (such as myself :smile:) the untar functionality?

**Comment by c4milo** [comment]
fair enough! Thanks for your PR @davidsiefert!

**Comment by davidsiefert** [comment]
Thanks!!

**Pull request merged**
